<a href="https://colab.research.google.com/github/royalflushallin/Machine-Learning/blob/main/MNIST_svmLinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing datasets

In [2]:
dataset = pd.read_csv('mnist_train.csv')
X_train = dataset.iloc[:, 1:].values
y_train = dataset.iloc[:, 0].values

In [3]:
dataset = pd.read_csv('mnist_test.csv')
X_test = dataset.iloc[:, 1:].values
y_test = dataset.iloc[:, 0].values

Feature scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Training the multi-class SVM-linear kernel model

In [5]:
from sklearn.svm import SVC
classifier = SVC(random_state=0, kernel = 'linear', decision_function_shape='ovr')
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

Predicting results

In [6]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
y_pred_train = classifier.predict(X_train)

[[2 2]
 [1 1]
 [0 0]
 ...
 [4 4]
 [5 5]
 [6 6]]


Test-set Confusion Matrix 

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 951    0    5    2    2    8    8    2    1    1]
 [   0 1119    6    2    0    1    2    1    4    0]
 [  10   13  956   11    7    4    5    6   18    2]
 [   7    1   15  941    0   16    1    6   19    4]
 [   3    2   18    1  929    0    3    5    4   17]
 [   7    6    7   41    6  789   12    2   19    3]
 [  12    3   13    1    8   17  902    0    2    0]
 [   2    8   23   13   10    1    0  944    5   21]
 [  12    6   11   28    8   24    9    6  858   12]
 [   6    7    6   10   36    4    1   23   13  903]]


0.9292929292929293

Training-set Confusion Matrix 

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
accuracy_score(y_train, y_pred_train)

[[5922    0    0    0    0    0    0    0    1    0]
 [   0 6737    0    0    0    0    0    0    5    0]
 [   4    6 5878   29    4    0    4    1   32    0]
 [   5    7   64 5933    2   68    0    1   45    6]
 [   0    6    0    1 5771    0    0    0    0   64]
 [   8    8    6  101    9 5243   11    0   32    2]
 [   1    0    1    0    1    4 5911    0    0    0]
 [   0    2    8    7   16    0    0 6157    0   75]
 [  14   27   24   65    4   61    1    4 5644    7]
 [   1    7    2   10   79    3    0  110    9 5728]]


0.9820830347172453