<a href="https://colab.research.google.com/github/royalflushallin/Machine-Learning/blob/main/MNIST_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing datasets

In [2]:
dataset_train = pd.read_csv('mnist_train.csv')
X_train = dataset_train.iloc[:, 1:].values
y_train = dataset_train.iloc[:, 0].values

In [3]:
dataset_test = pd.read_csv('mnist_test.csv')
X_test = dataset_test.iloc[:, 1:].values
y_test = dataset_test.iloc[:, 0].values

Feature scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Training the multi-class Logistic Regression model

In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, multi_class='ovr', max_iter=1000)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=0,
                   solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

Predicting results

In [8]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [1 1]
 [0 0]
 ...
 [4 4]
 [5 5]
 [6 6]]


Formulating the Confusion Matrix

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 960    0    3    1    0    5    6    3    1    1]
 [   0 1111    4    2    0    1    5    1   11    0]
 [  11    9  911   20    9    5   13   14   37    3]
 [   4    1   16  919    2   25    4   10   20    9]
 [   1    4    5    6  914    0    9    3    5   35]
 [   8    2    0   39   11  770   18    7   30    7]
 [   8    4    7    1    5   20  910    1    2    0]
 [   4    9   23    5    7    2    1  941    6   29]
 [  11   14    5   22   13   28   10   12  847   12]
 [   7    8    2   15   31   13    0   28   13  892]]


0.9175917591759176

In [10]:
from sklearn.metrics import multilabel_confusion_matrix
m_cm = multilabel_confusion_matrix(y_test, y_pred)
print(m_cm)

[[[8965   54]
  [  20  960]]

 [[8813   51]
  [  24 1111]]

 [[8902   65]
  [ 121  911]]

 [[8878  111]
  [  91  919]]

 [[8939   78]
  [  68  914]]

 [[9008   99]
  [ 122  770]]

 [[8975   66]
  [  48  910]]

 [[8893   79]
  [  86  941]]

 [[8900  125]
  [ 127  847]]

 [[8894   96]
  [ 117  892]]]
