<a href="https://colab.research.google.com/github/royalflushallin/Machine-Learning/blob/main/MNIST_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing libraries

In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing datasets

In [32]:
dataset_train = pd.read_csv('mnist_train.csv')
X_train = dataset_train.iloc[:, 1:].values
y_train = dataset_train.iloc[:, 0].values

In [33]:
dataset_test = pd.read_csv('mnist_test.csv')
X_test = dataset_test.iloc[:, 1:].values
y_test = dataset_test.iloc[:, 0].values

Feature scaling

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Training the multi-class Logistic Regression model

In [35]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, multi_class='ovr', max_iter=1000)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=0,
                   solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

Predicting results

In [36]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
y_pred_train = classifier.predict(X_train)

[[2 2]
 [1 1]
 [0 0]
 ...
 [4 4]
 [5 5]
 [6 6]]


Formulating the Confusion Matrix

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 960    0    3    1    0    5    6    3    1    1]
 [   0 1111    4    2    0    1    5    1   11    0]
 [  11    9  911   20    9    5   13   14   37    3]
 [   4    1   16  919    2   25    4   10   20    9]
 [   1    4    5    6  914    0    9    3    5   35]
 [   8    2    0   39   11  770   18    7   30    7]
 [   8    4    7    1    5   20  910    1    2    0]
 [   4    9   23    5    7    2    1  941    6   29]
 [  11   14    5   22   13   28   10   12  847   12]
 [   7    8    2   15   31   13    0   28   13  892]]


0.9175917591759176

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
accuracy_score(y_train, y_pred_train)

[[5811    1   14    9    6   14   28    3   35    2]
 [   1 6601   29   13    5   21    2   11   52    7]
 [  35   45 5457   80   53   21   53   61  136   17]
 [  21   22  140 5524    9  161   21   51  118   64]
 [   7   23   30    7 5512   11   26   16   51  159]
 [  45   20   36  155   56 4843   89   14  112   50]
 [  29   10   28    3   25   84 5707    3   26    3]
 [  13   18   54    8   53    7    4 5925   18  165]
 [  44  116   60  140   34  144   41   24 5164   84]
 [  26   18   19  100  168   45    2  182   46 5343]]


0.9314655244254071

In [ ]:
from sklearn.metrics import multilabel_confusion_matrix
m_cm = multilabel_confusion_matrix(y_test, y_pred)
print(m_cm)