<a href="https://colab.research.google.com/github/royalflushallin/Machine-Learning/blob/main/MNIST_svmKernel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing libraries

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing datasets

In [6]:
dataset = pd.read_csv('mnist_train.csv')
X_train = dataset.iloc[:, 1:].values
y_train = dataset.iloc[:, 0].values

In [7]:
dataset = pd.read_csv('mnist_test.csv')
X_test = dataset.iloc[:, 1:].values
y_test = dataset.iloc[:, 0].values

Feature scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Training the multi-class SVM-rbf kernel model

In [9]:
from sklearn.svm import SVC
classifier = SVC(random_state=0, kernel = 'rbf', decision_function_shape='ovr')
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

Predicting results

In [10]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
y_pred_train = classifier.predict(X_train)

[[2 2]
 [1 1]
 [0 0]
 ...
 [4 4]
 [5 5]
 [6 6]]


Test-set Confusion Matrix 

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 968    0    1    1    0    3    3    2    2    0]
 [   0 1127    3    0    0    1    2    0    2    0]
 [   5    1  996    2    2    0    1   15    9    1]
 [   0    0    4  979    1    7    0   12    7    0]
 [   0    0   12    0  944    2    4    7    3   10]
 [   2    0    1   10    2  854    6    8    7    2]
 [   6    2    1    0    4    8  930    2    5    0]
 [   1    6   13    2    3    0    0  989    0   13]
 [   3    0    4    6    6    9    3   14  926    3]
 [   4    6    5   11   12    2    0   20    3  946]]


0.965996599659966

Training-set Confusion Matrix 

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
accuracy_score(y_train, y_pred_train)

[[5896    2    0    1    1    3   10    1    8    1]
 [   1 6690   16    7    5    0    1    8    5    9]
 [   8    6 5898    4    9    1    1   14   14    3]
 [   0    7   17 6011    3   25    0   20   36   12]
 [   2   10    6    0 5763    0    7    4    2   48]
 [   6    3    5   33    6 5341   16    1    7    2]
 [  13    5    1    0    5   12 5877    0    5    0]
 [   1   21   17    3   17    0    0 6175    1   30]
 [   5   26    7   22    7   15    7    7 5749    6]
 [   6    8    2   29   44    5    1   46   12 5796]]


0.9866164436073934